config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  root 'home#index'

  get '/logout', to: 'home#logout'

  resources :battle
  resources :hashtag
  get '/battle/:battle_id/chartdata', to: 'battle#pie_chart_data', as: 'pie_chart_data'
  get '/battle/:battle_id/stackedlinechartdata', to: 'battle#stacked_line_chart_data', as: 'stacked_line_chart_data'

  get '/me', to: 'user#show', as: 'show_user'
  get '/me/battle', to: 'battle#user_battles', as: 'battle_index_user'
  get '/me/hashtag', to: 'hashtag#user_hashtags', as: 'hashtag_index_user'

  get '/me/access_token', to: 'user#generate_access_token', as: 'generate_access_token'

  get '/hashtag/:hashtag_id/evolutionchartdata', to: 'hashtag#evolution_chart_data', as: 'evolution_chart_data'
  get '/hashtag/:id/update_count', to: 'hashtag#update_count', as: 'update_count'

  get '/auth/twitter/callback', to: 'home#callback'
  get '/auth/failure', to: 'home#failure'

  mount BattleHashtagAPI, at: '/api'
  

end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_and_belongs_to_many :battles
  has_many :daily_hashtag_counts

  validates_format_of :name, :with => /[^\s[[:punct:]]]+/, message: 'Hashtag name must not contain punctuation nor whitespaces.'
  validates_format_of :name, :with => /\A#/, message: 'Hashtag name must start with a \'#\'.'

  # Gets count of hashtag retrieved for all the data we've got
  # Sums all the daily count for the hashtag
  def get_total_count
    daily_hashtag_counts.map(&:count).inject(0) { |sum, c| sum += c }
  end

  # Gets count of hashtag between two dates
  # Sums all the daily count for the hashtag between the dates provided
  def get_count_between(before: Date.today.beginning_of_day, now: Date.today.end_of_day)
    daily_hashtag_counts.where(last_refresh: before.beginning_of_day..now.end_of_day).map(&:count).inject(0) { |sum, c| sum += c }
  end

  def get_last_tweet_id(at: Time.now)
    dhc = daily_hashtag_counts.where(last_refresh: at.beginning_of_day..at.end_of_day).first
    dhc.try(:last_tweet_id)
  end

  # Returns representation of the Hashtag
  # {name: Hashtag.name, data: [ [date: date1, count: count1].. ]}
  def get_stacked_evolution_data(from: Date.today)
    data        = {}
    data[:name] = name
    data[:data] = []
    daily_hashtag_counts.where(last_refresh: [from..Time.now]).order(:last_refresh).each do |dhc|
      data[:data] << [dhc.count, dhc.last_refresh.strftime('%d-%m-%Y')]
    end
    sum         = 0
    data[:data].map! { |c| [c[1], sum += c[0]] }
    data
  end

  # Sets the count for the hashtag at a given moment
  # Updates the daily_count or create one if it doesn't exist yet
  # Using battle's user credentials
  def update_count(add: 0, at: Time.now, last_tweet_id: nil)
    daily_count               = daily_hashtag_counts.where(last_refresh: at.beginning_of_day..at.end_of_day).first || DailyHashtagCount.new(hashtag: self, count: 0)
    daily_count.last_refresh  = at
    daily_count.last_tweet_id = last_tweet_id
    daily_count.count        += add
    daily_count.save!
  end
end

app/controllers/hashtag_controller.rb
class HashtagController < ApplicationController
  include ApplicationHelper

  before_action :require_login, only: :user_hashtags

  # List of hashtags
  def index
    @hashtags = Hashtag.all
    @user     = current_user
  end

  # List of hashtags used by logged user
  def user_hashtags
    @hashtags = Hashtag.joins(:battles).where("battles.user_id = ?", current_user.id).includes(:battles).distinct
  end

  # Get a hashtag used
  def show
    @hashtag = Hashtag.find(params[:id])
    @user    = current_user
  end

  # Update a hashtag using logged user credential
  def update_count
    hashtag       = Hashtag.find(params[:id])
    return head :unauthorized unless current_user

    at            = Time.now
    twitter       = TwitterInterface.new(current_user)
    count         = twitter.fetch_tweet_count(hashtag, at)
    last_tweet_id = twitter.last_tweet_id

    hashtag.update_count(add: count, last_tweet_id: last_tweet_id)
    render nothing: true, status: 204, content_type: 'text/html' 
  end

  # Get Evolution Chart data of hashtag
  def evolution_chart_data
    hashtag = Hashtag.find(params[:hashtag_id])
    result  = [hashtag.get_stacked_evolution_data(from: hashtag.created_at)]
    
    render json: result
  end

end

app/views/hashtag/_evolution_chart.html.erb
<%= line_chart evolution_chart_data_path(hashtag), refresh: 10 %>

app/views/hashtag/_hashtags.html.erb
<ul>
  <% hashtags.each do |hashtag| %>
    <li><%= link_to hashtag.name, hashtag_path(hashtag) %> used in
      <ul>
        <% hashtag.battles.each do |battle| %>
          <li><%= link_to battle.display_name, battle_path(battle) %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/hashtag/index.html.erb
<h2>All Hashtags</h2>

<%= render partial: 'hashtags' , locals: { hashtags: @hashtags } %>

app/views/hashtag/show.html.erb
<h2>Hashtag <%= @hashtag.name%></h2>

<p>Overall count since <%= @hashtag.created_at.strftime("%m/%d/%y") %> : <%= @hashtag.get_total_count %></p>
<p>Day by Day evolution :</p>
<ul>
  <% @hashtag.daily_hashtag_counts.order(:last_refresh).each do |count| %>
    <li>
      <%= count.last_refresh.strftime("%m/%d/%y") %> - <%= count.count %> tweets
    </li>
  <% end %>
</ul>

<%= render partial: "evolution_chart", locals: { hashtag: @hashtag } %>

<script>
  $('[data-toggle="tooltip"]').tooltip(); 
  $(document).ready(function () {
    $.ajax({
      url: "<%= url_for update_count_path(@hashtag) %>"
    })
  })
</script>

app/views/hashtag/user_hashtags.html.erb
<h2>Your Hashtags</h2>

<ul>
  <% @hashtags.each do |hashtag| %>
    <li><%= link_to hashtag.name, hashtag_path(hashtag) %> used in
      <ul>
        <% hashtag.battles.each do |battle| %>
          <li><%= link_to battle.display_name, battle_path(battle) %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>