config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  root 'home#index'

  get '/logout', to: 'home#logout'

  resources :battle
  resources :hashtag
  get '/battle/:battle_id/chartdata', to: 'battle#pie_chart_data', as: 'pie_chart_data'
  get '/battle/:battle_id/stackedlinechartdata', to: 'battle#stacked_line_chart_data', as: 'stacked_line_chart_data'

  get '/me', to: 'user#show', as: 'show_user'
  get '/me/battle', to: 'battle#user_battles', as: 'battle_index_user'
  get '/me/hashtag', to: 'hashtag#user_hashtags', as: 'hashtag_index_user'

  get '/me/access_token', to: 'user#generate_access_token', as: 'generate_access_token'

  get '/hashtag/:hashtag_id/evolutionchartdata', to: 'hashtag#evolution_chart_data', as: 'evolution_chart_data'
  get '/hashtag/:id/update_count', to: 'hashtag#update_count', as: 'update_count'

  get '/auth/twitter/callback', to: 'home#callback'
  get '/auth/failure', to: 'home#failure'

  mount BattleHashtagAPI, at: '/api'
  

end

app/models/battle.rb
class Battle < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :hashtags
  accepts_nested_attributes_for :hashtags, :reject_if => lambda { |h| h[:name].blank? }
  validates :hashtags, length: { minimum: 2, maximum: 5, too_long: "%{count} is the maximum number of hashtags", too_short: "%{count} is the minimum number of hashtags" }

  # Update Hashtags linked to Battle using User token
  def update_hashtags(at: Time.now)
    hashtags.each do |h|
       twitter       = TwitterInterface.new(user)
       count         = twitter.fetch_tweet_count(h, at)
       last_tweet_id = twitter.last_tweet_id
       h.update_count(add: count, last_tweet_id: last_tweet_id, at: at)
    end
  end

  # Get Battle name using its hashtags
  def display_name
    hashtags.map(&:name).join(' vs ')
  end

end

app/controllers/battle_controller.rb
class BattleController < ApplicationController
  include ApplicationHelper

  before_action :require_login, only: [:new, :create, :user_battles]

  # Instantiate new Battle with - by default - 2 hashtags
  def new
    @battle      = Battle.new 
    @battle.user = current_user

    2.times { @battle.hashtags.build }
  end

  # Create Battle with unique Hashtags
  def create
    @battle        = Battle.new
    @battle.user   = current_user

    params[:battle][:hashtags_attributes].each do |i, hashtag|
      next if hashtag[:name].blank?
      @battle.hashtags << Hashtag.find_or_create_by(name: hashtag[:name])
    end

    # At least 2 valid hashtags - maximum 5
    if @battle.save
      redirect_to @battle
    else
      render new_battle_path(@battle), alert: @battle.errors
    end
  end

  # Gets a Battle
  def show
    @battle  = Battle.find(params[:id])
    @user = current_user
  end

  # Show all Battles (Visitor view)
  def index
    @battles = Battle.all
    @user = current_user
  end

  # Battles of a user (Logged user)
  def user_battles
    @battles = current_user.battles
  end

  # Pie Chart data of the Battle
  def pie_chart_data
    battle = Battle.find(params[:battle_id])
    
    render json: battle.hashtags.map { |h| [h.name, h.get_count_between(before: battle.created_at)] }
  end

  # Stacked Line Chart data of the Battle
  def stacked_line_chart_data
    battle = Battle.find(params[:battle_id])
    data   = []

    battle.hashtags.each do |h|
      data << h.get_stacked_evolution_data(from: battle.created_at)
    end

    render json: data
  end

end

app/views/battle/_battles.html.erb
<ul>
<% battles.each do |battle| %>
  <li><%= link_to battle.display_name, battle_path(battle)%></li>
<% end %>
</ul>

app/views/battle/_hashtag_fields.html.erb
<li class="nested-fields">
  <%= f.label      :name %>
  <%= f.text_field :name %>
  <%= link_to_remove_association "Remove hashtag", f %>
</li>

app/views/battle/_pie_chart.html.erb
<%= pie_chart pie_chart_data_path(battle), refresh: 10 %>

app/views/battle/_stacked_line_chart.html.erb
<%= line_chart stacked_line_chart_data_path(battle), refresh: 10 %>

app/views/battle/index.html.erb
<h2>All battles</h2>

<%= render partial: 'battles', locals: { battles: @battles } %>

app/views/battle/new.html.erb
<% if !@battle.errors[:hashtags].blank? %>
  <p class="list-group-item list-group-item-danger"><%= @battle.errors[:hashtags].join(',') %></p> 
<% end %>

<%= form_for @battle, url: {action: :create} do |f| %>
  <% if @battle.errors['hashtags.name'] %>
    <ul>
      <% @battle.errors['hashtags.name'].each do |error| %>
        <li class="list-group-item list-group-item-danger"><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  Hashtags :
  <ul>
    <%= f.fields_for :hashtags do |ff| %>
      <%= render 'hashtag_fields', f: ff %>
    <% end %>
    <p><%= link_to_add_association "Add hashtag", f, :hashtags %></p>
  </ul>

  <%= submit_tag 'Create battle !' %>
<% end %>

app/views/battle/show.html.erb
<h2>Displaying Battle <%= @battle.display_name %></h2>

<%= render partial: "pie_chart", locals: { battle: @battle } %>

<%= render partial: "stacked_line_chart", locals: { battle: @battle } %>

<script>
  $('[data-toggle="tooltip"]').tooltip(); 
  $(document).ready(function () {
      <% @battle.hashtags.each do |hashtag| %>
        $.ajax({
          url: "<%= url_for update_count_path(hashtag) %>"
        })
      <% end %>
  })
</script>

app/views/battle/user_battles.html.erb
<h2>Your battles</h2>

<%= render partial: 'battles' , locals: { battles: @battles } %>