config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  root 'home#index'

  get '/logout', to: 'home#logout'

  resources :battle
  resources :hashtag
  get '/battle/:battle_id/chartdata', to: 'battle#pie_chart_data', as: 'pie_chart_data'
  get '/battle/:battle_id/stackedlinechartdata', to: 'battle#stacked_line_chart_data', as: 'stacked_line_chart_data'

  get '/me', to: 'user#show', as: 'show_user'
  get '/me/battle', to: 'battle#user_battles', as: 'battle_index_user'
  get '/me/hashtag', to: 'hashtag#user_hashtags', as: 'hashtag_index_user'

  get '/me/access_token', to: 'user#generate_access_token', as: 'generate_access_token'

  get '/hashtag/:hashtag_id/evolutionchartdata', to: 'hashtag#evolution_chart_data', as: 'evolution_chart_data'
  get '/hashtag/:id/update_count', to: 'hashtag#update_count', as: 'update_count'

  get '/auth/twitter/callback', to: 'home#callback'
  get '/auth/failure', to: 'home#failure'

  mount BattleHashtagAPI, at: '/api'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :battles
  has_one :token, -> { order 'created_at DESC' }, class_name: Doorkeeper::AccessToken, foreign_key: :resource_owner_id

  ###         ATTRIBUTES         ###
  ### STRING name                ###
  ### STRING access_token        ###
  ### STRING secret_access_token ###
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include ApplicationHelper
  before_action :require_login

  def show
    @user          = current_user
    @access_token = Doorkeeper::AccessToken.where(:application_id => Doorkeeper::Application.first.id, :resource_owner_id => current_user.id, :revoked_at => nil).first

  end

  def generate_access_token
    access_token = Doorkeeper::AccessToken.create!(:application_id => Doorkeeper::Application.first.id, :resource_owner_id => current_user.id)
    redirect_to show_user_path
  end  

end

app/views/user/show.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Twitter ID</th>
    <th>Twitter Name</th>
    <th>API Access Token</th>
  </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user.sid %></td>
      <td><%= @user.name %></td>
      <td>
        <% if @access_token %>
          <%= @access_token.try(:token) %>
        <% else %>
          <%= link_to('Generate an API Access Token', generate_access_token_path) %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>