config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper

  root 'home#index'

  get '/logout', to: 'home#logout'

  resources :battle
  resources :hashtag
  get '/battle/:battle_id/chartdata', to: 'battle#pie_chart_data', as: 'pie_chart_data'
  get '/battle/:battle_id/stackedlinechartdata', to: 'battle#stacked_line_chart_data', as: 'stacked_line_chart_data'

  get '/me', to: 'user#show', as: 'show_user'
  get '/me/battle', to: 'battle#user_battles', as: 'battle_index_user'
  get '/me/hashtag', to: 'hashtag#user_hashtags', as: 'hashtag_index_user'

  get '/me/access_token', to: 'user#generate_access_token', as: 'generate_access_token'

  get '/hashtag/:hashtag_id/evolutionchartdata', to: 'hashtag#evolution_chart_data', as: 'evolution_chart_data'
  get '/hashtag/:id/update_count', to: 'hashtag#update_count', as: 'update_count'

  get '/auth/twitter/callback', to: 'home#callback'
  get '/auth/failure', to: 'home#failure'

  mount BattleHashtagAPI, at: '/api'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HashtagBattle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
  <div class="navbar-header">
    <%= link_to "HashtagBattle-POC", root_path, :class => "navbar-brand" %>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li>
          <a class="btn dropdown-toggle" type="button" data-toggle="dropdown">Battles
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All battles", battle_index_path %></li>
            <li <%= 'class=disabled' unless @user %>><%= link_to "My battles", battle_index_user_path %></li>
            <li><%= link_to "Create battle", new_battle_path %></li>
          </ul>
      </li>
      <li>
          <a class="btn dropdown-toggle" type="button" data-toggle="dropdown">Hashtags
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All hashtags", hashtag_index_path %></li>
            <li <%= 'class=disabled' unless @user %>><%= link_to "My hashtag", hashtag_index_user_path %></li>
          </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if @user %>
        <li><%= link_to @user.name, show_user_path %></li>
        <li><%= link_to 'Log out', controller: :home, action: :logout %></li>
      <% else %>
        <li><%= link_to 'Sign in with Twitter', twitter_auth_path %></li>
      <% end %>
    </ul>
  </div>
</nav>
<%= yield %>

<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

</body>
</html>